//
//  CallProtocol.h
//  Callee
//
//  Created by Ivan Tkachenko on 4/8/17.
//  Copyright © 2017 Youshido. All rights reserved.
//

#import <Foundation/Foundation.h>

@protocol CallProtocol <NSObject>

@property (nonatomic, readonly) NSUUID *UUID;       // Autogenerated UUID
@property (nonatomic, readonly) NSString *handle;   // Unique opponent identifier (phone number or login)

// Call status identifiers
@property (nonatomic) BOOL hasVideo;
@property (nonatomic) BOOL onHold;
@property (nonatomic) BOOL muted;

// Timestamps of call lifecycle
@property (nonatomic, strong) NSDate *startDate;
@property (nonatomic, strong) NSDate *connectingDate;
@property (nonatomic, strong) NSDate *connectedDate;
@property (nonatomic, strong) NSDate *endDate;

@optional
@property (nonatomic, readonly) NSString *localizedCallerName;      // Caller name

@end
